import bs4
#exampleFile = open("example.html")
#exampleSoup = bs4.BeautifulSoup(exampleFile.read(), "html.parser")
#elems = exampleSoup.select("#author")
#type(elems)
#print(len(elems))
#type(elems[0])
#str(elems[0])
#print(elems[0].getText())
import requests
res = requests.get('https://www.sanignacio.pr/sobre-csi/historia-del-colegio')
res.raise_for_status()
SanIgnaciopr = bs4.BeautifulSoup(res.content, 'html.parser')
elems = SanIgnaciopr.select('p')
print(type(SanIgnaciopr))
print(len(elems))
#print(str(elems))
print(elems[2].getText())
