print("Welcome to El Alfa concert")
print("The cost for each seat is as follows: Arena = $75, Vision Limitada = $50, Nivel Superior = $40")
Arena = int(input("How many Arena tickets will you buy? = "))
Vision_Limitada = int(input("How many Vision Limitada tickets will you buy? = "))
Nivel_Superior = int(input("How many Nivel Superior tickets will you buy?  = "))
print("Your total cost of Arena seating is:", Arena * 75)
print("Your total cost of Vision Limitada seating is:", Vision_Limitada * 50)
print("Your total cost of Nivel Superior seating is:", Nivel_Superior * 40)
print("Your total cost of seating is:", (Arena * 75 + Vision_Limitada * 50 + Nivel_Superior * 40)*1.115)
